# reference https://github.com/jenkinsci/docker/issues/177
# sudo mkdir -p $PWD/mnt/sdb/jenkins-data
# sudo chown -R 1000:1000 $PWD/mnt/sdb/jenkins-data
version: '3'
services:
  jenkins:
    image: 'jenkins/jenkins:2.60.3'
    container_name: jenkins
    restart: always
    privileged: yes
    ports:
      - '8001:8080'
      - '50000:50000'
    volumes:
      - $PWD/mnt/sdb/jenkins-data:/var/jenkins_home:Z
    environment:
      - TZ=Asia/Taipei
    #  - JAVA_OPTS=" -Djenkins.install.runSetupWizard=false"
      - JENKINS_OPTS="--prefix=/jenkins"


