# reference https://github.com/jenkinsci/docker/issues/177
# sudo mkdir -p $PWD/mnt/sdb/jenkins-data
# sudo chown -R 1000:1000 $PWD/mnt/sdb/jenkins-data
services:
  jenkins:
    image: 'jenkins/jenkins:lts-jdk17'
    container_name: jenkins
    restart: always
    privileged: true
    network_mode: host
#    ports:
#      - '8001:8080'
#      - '5000:5000'
    # extra_hosts:
    #   - "mirrors.tuna.tsinghua.edu.cn:127.0.0.1"
    volumes:
      - $PWD/mnt/sdb/jenkins-data:/var/jenkins_home:Z
    environment:
      - TZ=Asia/
      - JENKINS_UC_DOWNLOAD=http://ftp.yz.yamagata-u.ac.jp/pub/misc/jenkins/
      - JENKINS_PREFIX="/jenkins"
      - JENKINS_OPTS=--httpPort=8001 --prefix=/jenkins
      - jenkins.model.Jenkins.slaveAgentPort=5000


